### ISSUE TITLE
ERR_INVALID_ARG_TYPE'

### ISSUE THREAD

**Issue by ashwinrajanta** [WebPageTest/webpagetest-api#174]
i'm running a webpage test inside a docker container on top of Debian 11. 

My Webpagetest version

```
root@ea9d12df0532:/usr/local/bin# webpagetest -V
0.7.1

```
How do i resolve the issue? Kindly anyone help me here. 

```
root@ea9d12df0532:/usr/local/bin# webpagetest --server http://localhost test -l Test -r 1 -y Native www.youtube.com
events.js:291
      throw er; // Unhandled 'error' event
      ^

TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer. Received undefined
    at validChunk (_stream_writable.js:281:10)
    at WriteStream.Writable.write (_stream_writable.js:316:21)
    at output (/usr/local/lib/node_modules/webpagetest/bin/webpagetest:27:18)
    at Function.formatData (/usr/local/lib/node_modules/webpagetest/bin/webpagetest:68:5)
    at callbackYield (/usr/local/lib/node_modules/webpagetest/lib/webpagetest.js:166:14)
    at WebPageTest.apiCallback (/usr/local/lib/node_modules/webpagetest/lib/webpagetest.js:240:9)
    at IncomingMessage.onEnd (/usr/local/lib/node_modules/webpagetest/lib/webpagetest.js:150:13)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on WriteStream instance at:
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at validChunk (_stream_writable.js:284:5)
    at WriteStream.Writable.write (_stream_writable.js:316:21)
    [... lines matching original stack trace ...]
    at endReadableNT (_stream_readable.js:1241:12) {
  code: 'ERR_INVALID_ARG_TYPE'
}

```

**Comment by slightlyoff** [comment]
This is the result of a busted check in the main script file for outputting binary data to a file. I'm working on a fix now.
